### PR TITLE
Create Hebrew file - plugin.video.tvtoday_de

### PR DESCRIPTION
**Pull request by Eng2Heb**

### CODE REVIEW

**Comment by Collabsvito** [comment]
Very funny, German-Television in Hebrew :-)
Can you include version bump to 1.4.0 ?

**Comment by Eng2Heb** [comment]
Sure

**Comment by Collabsvito** [comment]
YES if you want ?!
If you create also a translation for "plugin.video.tvspielfilm_de", i can update both versions.
Because both Addons show the same content !

**Comment by Eng2Heb** [comment]
Sure.
I already translated also plugin.video.tvspielfilm_de
Thanks a lot

**Comment by Eng2Heb** [comment]
Hi,
Please merge the pull.

**Pull request closed without merging**
